spring:
  datasource:
    url: jdbc:h2:mem:orders-test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
services:
  catalog:
    base-url: http://localhost
  users:
    base-url: http://localhost
notifications:
  orders:
    to: tests@portfolio.local
